### ISSUE TITLE
完成项目 E-R 图

### ISSUE THREAD

**Issue by usedtolove** [HelloTZ/tz-business#2]
使用astah建立用例图
并提交到项目根目录下，以日期命名，
比如: 2015-9-21

**Comment by usedtolove** [comment]
已将 文件移至 /docs/uml/下,
请将类的属性精简，
属性中无需体现类名，
并且要注意规范。
比如：Employee类的EmpName属性改为 name即可。

**Comment by usedtolove** [comment]
test message 2

**Comment by zhq520134** [comment]
胡老师，E-R图修改完毕，并已提交到docs-UML-电子商务E-R图(改进版)分支中
