### ISSUE TITLE
准备 SpringData 知识点

### ISSUE THREAD

**Issue by usedtolove** [HelloTZ/tz-business#8]
为提高Dao的开发效率，
进行 SpringData 知识点学习和使用，
官网：http://projects.spring.io/spring-data/

**Comment by usedtolove** [comment]
完成学习后，
给出10页左右的ppt，
给出项目链接即可。

**Comment by ChaiLongLong** [comment]
项目链接:
https://github.com/ChaiLongLong/SpringData
