### ISSUE TITLE
准备 BeanValidation(JSR303) 知识点

### ISSUE THREAD

**Issue by usedtolove** [HelloTZ/tz-business#9]
为提高 SpringMVC  中参数校验的开发效率，
进行 BeanValidation 知识点学习和使用，
官网：http://hibernate.org/validator/

**Comment by usedtolove** [comment]
在自己的账户下，建立一个演示项目，
写一个 Hibernate BeanValidation HelloWorld，
并给出10页左右的ppt，
完成后给出项目链接。

**Comment by zhq520134** [comment]
https://github.com/zhq520134/zhq-validator

**Comment by zhq520134** [comment]
https://github.com/zhq520134/zhq-validator
